### ISSUE TITLE
Ideas for a more effective office

### ISSUE THREAD

**Issue by Logiqx** [Logiqx/wsw-tech#39]
Thoughts:

- Have a seperate office for doing results.
  - Quiet and less interruptions.
  - Need to consider the implications for the Motion server.
- Introduce a simple form for result queries.
  - Include tickbox to indicate whether it affects daily prizes during skippers meeting or weekly standings.
  - Missing runs or lower speeds than expected?
  - Queries can be prioritised and investigated at an appropriate time during the day.

**Comment by nickjpovey** [comment]
The room we use has a divider we could shut off the coffee end mid afternoon and let everyone else come in the wet end.

Or acquire some open plan office screens - the academy may have them.

If we had the room immediately above maybe connectivity, either wifi or cable through the windows, would be OK? I'll ask Sally if one exists that we may be able to have the use of.
------------------------
Request made and agreed as below:

Hi Nick,

No problem to register on Friday 6th and have it open until 19:00 and I have booked a small classroom as a quiet room for you.  The network cable would not be able to stay in all the time as the windows need to be closed for the alarm to set.

The Saturday you have your dinner/party so the building will be open later anyway.  I have put that you want 18:00 closing the rest of the week.

However, we will be reviewing all of our costs for events next year due to the increases in charges, not least for utilities and fuel.  When do you do your budget for next year and require a price from us by, please?

Many thanks,

Sally.

Sally Reynoldson
Events Supervisor
Weymouth and Portland National Sailing Academy

T:            01305 866001
E:            [sally.reynoldson@wpnsa.org.uk](mailto:sally.reynoldson@wpnsa.org.uk)
W:          [www.wpnsa.org.uk](http://www.wpnsa.org.uk/)
:         Weymouth and Portland National Sailing Academy
:          @WPNSA

WPNSA Ltd.  Company registered address:  Weymouth and Portland National Sailing Academy, Osprey Quay, Portland, Dorset, DT5 1SA  VAT Registration Number 750 570 638 Company Registration Number 3738770

-----Original Message-----
From: Nick Povey [<nick@speedsailing.com>](mailto:nick@speedsailing.com) 
Sent: 27 October 2022 21:57
To: Sally Reynoldson [<sally.reynoldson@wpnsa.org.uk>](mailto:sally.reynoldson@wpnsa.org.uk)
Subject: WSW 2023 and beyond

Hi Sally,

I'm getting involved in planning how best to run the 2023 Weymouth Speed Week whilst things are still fresh. For 2023 we will have our new GPS units and new results software, so there may be some head scratching that we will have to do!

Two enquiries if I may.

Would it be feasible to have a small "quiet" room for the duration of the week? Ideally immediately above the main room so we can drop a network cable down through the windows for connectivity if needed.

Could you arrange for 7pm 'lights out' on the Friday before and Saturday, and 6pm during the week? It really helped us this year.

Thank you

All the best

Nick

**Comment by nickjpovey** [comment]
[Weymouth Speed Week 2023 - What to take V3.docx](https://github.com/Logiqx/wsw-tech/files/9883090/Weymouth.Speed.Week.2023.-.What.to.take.V3.docx)

Everything in black has been procured and packed ready for October 2023! I've included two A4 notebooks where we, and the 'office' can keep a record of issues, requests, messages etc.  instead of using scraps of paper that get borrowed!

**Comment by Logiqx** [comment]
@nickjpovey - here's an idea to consider.

Queries that are raised by competitors can start life on paper, but we should also add them to the issues on wsw-results.

https://github.com/Logiqx/wsw-results/issues

That way, queries / issues can be dealt effectively (not lost on bits of paper) and the history can be retained.

We can also review the closed wsw-results issues for common themes.

**Comment by Logiqx** [comment]
I have recorded all of the issues during 2023 in the wsw-results project.

https://github.com/Logiqx/wsw-results/issues?q=is%3Aissue+

I'd like to keep the list of wsw-results issues specific to actual bugs, hardware faults, suspected faults, and user errors.

Ideas, improvements and general tasks can be recorded in the wsw-tech issues.

**Comment by Logiqx** [comment]
The quiet office worked really well this week.

Closing this issue as we now have effective ways of working for future years.
